package main

import (
	"fmt"

	"github.com/buildsthenetwork/builds-dhcp-server/internal/dhcp"
)

func main() {
	fmt.Println("Hello DHCP!")

	/*
		var msg dhcp.Message

		msg.OP = uint8(1)    // 1 bootrequest, 2 bootreply
		msg.HTYPE = uint8(1) // 10Mb is a historical reference. We just want ethernet.
		msg.HLEN = uint8(6)  // 6 byte mac address in CHADDR
		msg.HOPS = uint8(0)
		msg.XID = rand.Uint32()    // randomly generated by client
		msg.SECS = uint16(1)       // feels weird to count in seconds.
		msg.FLAGS = uint16(0x8000) // Broadcast flag set. Essentially 0 or 1, as MBZ must be 0 as it's reserved for future use.
		msg.CIADDR = uint32(0)
		msg.YIADDR = uint32(0)
		msg.SIADDR = uint32(0) // returned by server in DHCPOFFER and DHCPACK
		msg.GIADDR = uint32(0) // Relay Agent IP
		msg.CHADDR = [16]byte{0xaa, 0xaa, 0xaa, 0xbb, 0xbb, 0xbb}
		msg.SNAME = [64]byte{}
		msg.FILE = [128]byte{}
		msg.MAGIC_COOKIE = [4]byte{99, 130, 83, 99}
		msg.OPTIONS = []byte{}

		msg.Print()
	*/

	// dhcp.BindServer()

	msg := dhcp.ParseMessage([]byte{
		1,               // OP
		1,               // HTYPE
		6,               // HLEN
		0,               // HOPS
		198, 68, 40, 71, // XID
		0, 1, // SECS
		0, 0, // FLAGS
		0, 0, 0, 0, // CIADDR
		0, 0, 0, 0, // YIADDR
		0, 0, 0, 0, // SIADDR
		10, 10, 10, 10, // GIADDR
		0, 12, 41, 160, 218, 134, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, //CHADDR
		0, 0, 0, 0, 0, 0, 0, 0, // SNAME
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,

		0, 0, 0, 0, 0, 0, 0, 0, // FILE
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0,

		99, 130, 83, 99, // MAGIC COOKIE

		53, 1, 3, 61, 19, 255, 43, 148,
		52, 193, 0, 2, 0, 0, 171, 17,
		219, 240, 227, 75, 236, 207,
		239, 253, 55, 12, 1, 3, 6, 12,
		15, 26, 33, 42, 114, 119, 120,
		121, 57, 2, 5, 192, 50, 4, 192,
		168, 65, 128, 12, 11, 117, 98,
		117, 110, 116, 117, 45, 116, 101, 115, 116,
		255,
	})
	msg.Print()

}
