package main

import (
	"fmt"
	"math/rand"

	"github.com/buildsthenetwork/builds-dhcp-server/internal/dhcp"
)

func main() {
	fmt.Println("Hello DHCP!")

	var msg dhcp.Message

	msg.OP = uint8(1)    // 1 bootrequest, 2 bootreply
	msg.HTYPE = uint8(1) // 10Mb is a historical reference. We just want ethernet.
	msg.HLEN = uint8(6)  // 6 byte mac address in CHADDR
	msg.HOPS = uint8(0)
	msg.XID = rand.Uint32()    // randomly generated by client
	msg.SECS = uint16(1)       // feels weird to count in seconds.
	msg.FLAGS = uint16(0x8000) // Broadcast flag set. Essentially 0 or 1, as MBZ must be 0 as it's reserved for future use.
	msg.CIADDR = uint32(0)
	msg.YIADDR = uint32(0)
	msg.SIADDR = uint32(0) // returned by server in DHCPOFFER and DHCPACK
	msg.GIADDR = uint32(0) // Relay Agent IP
	msg.CHADDR = [16]byte{0xaa, 0xaa, 0xaa, 0xbb, 0xbb, 0xbb}
	msg.SNAME = [64]byte{}
	msg.FILE = [128]byte{}
	msg.MAGIC_COOKIE = [4]byte{99, 130, 83, 99}
	msg.OPTIONS = []byte{}

	msg.Print()

}
